service: cloudverse-flask-api

frameworkVersion: "2 || 3"

plugins:
    - serverless-wsgi
    - serverless-python-requirements

custom:
    wsgi:
        app: app.app
        packRequirements: false

provider:
    name: aws
    runtime: python3.8
    region: ca-central-1
    memorySize: 128

functions:
    api:
        handler: wsgi_handler.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true

package:
    individually: true
    exclude:
        - .env
        - .git/**
        - .github/**
        - .serverless/**
        - static/**
        - .cache/**
        - .pytest_cache/**
        - node_modules/**
